/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanpertemuan5;

/**
 *
 * @author LENOVO IDEAPAD
 */
public class Latihan2_MenghitungLuasSegitiga extends javax.swing.JFrame {

    /**
     * Creates new form Latihan1
     */
    public Latihan2_MenghitungLuasSegitiga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputAlas = new javax.swing.JTextField();
        inputTinggi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        luasSegitiga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura Md BT", 0, 13)); // NOI18N
        jLabel1.setText("Input Tinggi :");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 13)); // NOI18N
        jLabel2.setText("MENGHITUNG LUAS SEGITIGA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Futura Md BT", 0, 13)); // NOI18N
        jLabel3.setText("Input Alas   : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        inputAlas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAlasActionPerformed(evt);
            }
        });
        getContentPane().add(inputAlas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 210, -1));

        inputTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTinggiActionPerformed(evt);
            }
        });
        getContentPane().add(inputTinggi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 210, -1));

        jButton1.setFont(new java.awt.Font("Futura Md BT", 1, 13)); // NOI18N
        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 125, -1, 40));

        luasSegitiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasSegitigaActionPerformed(evt);
            }
        });
        getContentPane().add(luasSegitiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 200, 90));

        jLabel4.setFont(new java.awt.Font("Futura Md BT", 0, 13)); // NOI18N
        jLabel4.setText("Luas Segitiga :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputAlasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAlasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAlasActionPerformed

    private void inputTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTinggiActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int alas, tinggi;
        double luas;
        alas = Integer.valueOf(inputAlas.getText());
        tinggi = Integer.valueOf(inputTinggi.getText());
        luas = (double)(alas * tinggi)/2;
        luasSegitiga.setText(String.valueOf(luas));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void luasSegitigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasSegitigaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_luasSegitigaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2_MenghitungLuasSegitiga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Latihan2_MenghitungLuasSegitiga().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputAlas;
    private javax.swing.JTextField inputTinggi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField luasSegitiga;
    // End of variables declaration//GEN-END:variables
}
