/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package latihanpertemuan5;

/**
 *
 * @author LENOVO IDEAPAD
 */
public class Latihan2 extends javax.swing.JFrame {

    /**
     * Creates new form Latihan2
     */
    public Latihan2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jenkel = new javax.swing.JLabel();
        rblaki = new javax.swing.JRadioButton();
        rbpr = new javax.swing.JRadioButton();
        txtnobp = new javax.swing.JTextField();
        txtnm = new javax.swing.JTextField();
        txtalmt = new javax.swing.JTextField();
        txthp = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txthsl = new javax.swing.JTextArea();
        jurusan = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jLabel1.setText("Jurusan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("Futura Md BT", 1, 18)); // NOI18N
        jLabel2.setText("BIODATA MAHASISWA");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jLabel3.setText("No. BP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jLabel4.setText("Nama");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel5.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jLabel5.setText("No. HP");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        jenkel.setFont(new java.awt.Font("Futura Bk BT", 1, 13)); // NOI18N
        jenkel.setText("Jenis Kelamin");
        getContentPane().add(jenkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        rblaki.setText("Laki - Laki");
        rblaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rblakiActionPerformed(evt);
            }
        });
        getContentPane().add(rblaki, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, -1, -1));

        rbpr.setText("Perempuan");
        rbpr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbprActionPerformed(evt);
            }
        });
        getContentPane().add(rbpr, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtnobp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnobpActionPerformed(evt);
            }
        });
        getContentPane().add(txtnobp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 330, -1));

        txtnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmActionPerformed(evt);
            }
        });
        getContentPane().add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 330, -1));

        txtalmt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtalmtActionPerformed(evt);
            }
        });
        getContentPane().add(txtalmt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 330, 50));

        txthp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthpActionPerformed(evt);
            }
        });
        getContentPane().add(txthp, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 330, -1));

        txthsl.setColumns(20);
        txthsl.setRows(5);
        jScrollPane1.setViewportView(txthsl);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 350, 140));

        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistem informasi", "Informatika", "Desain Komunikasi Visual", "Bisnis Digital", "Manajemen Ritel" }));
        jurusan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jurusanItemStateChanged(evt);
            }
        });
        getContentPane().add(jurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 330, 30));

        jButton1.setFont(new java.awt.Font("Futura Md BT", 1, 36)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 110, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rblakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rblakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rblakiActionPerformed

    private void rbprActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbprActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbprActionPerformed

    private void txtnobpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnobpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnobpActionPerformed

    private void txtnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmActionPerformed

    private void txtalmtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtalmtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtalmtActionPerformed

    private void txthpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthpActionPerformed

    private void jurusanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jurusanItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jurusanItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String jenkel="";
        if(rblaki.isSelected()){
            jenkel = "Laki - Laki";
        }
        else if (rbpr.isSelected()){
            jenkel = "Perempuan";
    }//GEN-LAST:event_jButton1ActionPerformed

    txthsl.setText("BIODATA MAHASISWA"
                  + "\n No. BP\t : " + txtnobp.getText()
                  + "\n Nama\t : " + txtnm.getText()
                  + "\n No. HP\t : " + txthp.getText()
                  + "\n Alamat\t : " + txtalmt.getText()
                  + "\n Jenis Kelamin\t : " + jenkel
                  + "\n Jurusan\t : " + jurusan.getSelectedItem().toString());
    txtnobp.setEnabled(false);
    txtnm.setEnabled(false);
    txthp.setEnabled(false);
    txtalmt.setEnabled(false);
    rblaki.setEnabled(false);
    rbpr.setEnabled(false);
    jurusan.setEnabled(false);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Latihan2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Latihan2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jenkel;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JRadioButton rblaki;
    private javax.swing.JRadioButton rbpr;
    private javax.swing.JTextField txtalmt;
    private javax.swing.JTextField txthp;
    private javax.swing.JTextArea txthsl;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnobp;
    // End of variables declaration//GEN-END:variables
}
